### ISSUE TITLE
방 퇴사하기 테스트

### ISSUE THREAD

**Issue by orijoon98** [TeamHous/Hous-Server#115]
## 📌 Feature Issue
방 퇴사하기 테스트

## 📝 To-do

- [x] 방 퇴사하기 성공 케이스 테스트
- [x] afterEach 컬렉션 초기화 추가
- [x] prod, dev, test 환경 추가
- [x] test 환경에서만 테스트 가능하도록 추가
