### ISSUE TITLE
규칙 테스트

### ISSUE THREAD

**Issue by orijoon98** [TeamHous/Hous-Server#120]
## 📌 Feature Issue
규칙 테스트

## 📝 To-do

- [x] 규칙 생성 성공 테스트 추가
- [x] 규칙 수정 성공 테스트 추가
- [x] 규칙 삭제 성공 테스트 추가
