### ISSUE TITLE
이벤트 관련 api 테스트 코드 작성

### ISSUE THREAD

**Issue by hyejungg** [TeamHous/Hous-Server#197]
## 📌 Feature Issue

이벤트 관련 api 테스트 코드 작성

## 📝 To-do

- [x] 이벤트 추가 api 코드 작성
- [x] 이벤트 수정 api 코드 작성
- [x] 이벤트 조회 api 코드 작성
- [x] 이벤트 삭제 api 코드 작성
