### ISSUE TITLE
최종 리드미 작성

### ISSUE THREAD

**Issue by orijoon98** [TeamHous/Hous-Server#221]
## 📌 Feature Issue

최종 리드미 작성
## 📝 To-do

- [x] 중간과제의 README 보완
- [x] 서비스 핵심 기능 소개 (이미지 포함)
- [x] dependencies module ( package.json )
- [x] server architecture
