### ISSUE TITLE
사용자 관련 api 테스트 작성

### ISSUE THREAD

**Issue by hyejungg** [TeamHous/Hous-Server#27]
## 📌 Feature Issue

TDD를 하려고 했지만 잊고 있던 테스트 코드를 한 번 작성해보려 합니다 .. ^&^.. 

## 📝 To-do

- [x] 사용자 정보 조회 서비스 로직 test 코드 작성 
- [x] 사용자 정보 수정 서비스 로직 test 코드 작성
- [x] 사용자 정보 홈조회 서비스 로직 test 코드 작성 
- [x] 사용자 탈퇴하기 로직 test 코드 작성 
- [x] 사용자 성향 점수 등록 및 수정 test 코드 작성 
- [x] 룸메이트 조회 test 코드 작성
