### ISSUE TITLE
규칙 카테고리 추가/수정, 규칙 생성 시 조회에서 접근 권한 검사 추가

### ISSUE THREAD

**Issue by yjooooo** [TeamHous/Hous-Server#76]
## 📌 Feature Issue

- 규칙 카테고리 생성시 권한에 대한 검사 추가

## 📝 To-do

- [x] params의 roomId가 유저가 참가하고 있는 방인지 확인
- [x] params의 ruleCategoryId가 유저가 참가하고 있는 방의 규칙 카테고리인지 확인
- [x] 규칙 생성 시 조회의 roomId 도 참가하고 있는 방인지 확인
