### ISSUE TITLE
규칙 생성/삭제, 규칙 카테고리 삭제 api 수정 (규칙 개수 제한)

### ISSUE THREAD

**Issue by yjooooo** [TeamHous/Hous-Server#86]
## 📌 Feature Issue

- 한방의 규칙 개수 제한 -> 카테고리별 규칙 개수 제한으로 수정

## 📝 To-do

- [x] Room, RoomInfo : ruleCnt 삭제
- [x] RuleCategory, RuleCategoryInfo : ruleCnt 추가
- [x] 규칙 추가/삭제, 규칙 카테고리 추가/삭제 시 카테고리 별 규칙 개수 확인
  - [x] RuleService.createRule 수정
    - 규칙 생성 개수 제한 수정 -> 카테고리별 제한 20개_(updateRule에도 추가했음)_
    - 카테고리 id 존재하는지, 카테고리가 room에 포함되는지 확인
    - 규칙 카테고리의 ruleCnt + 1
  - [x] RuleService.deleteRule 수정
    - 규칙 카테고리의 ruleCnt - 1
  - [x] RuleService.deleteRuleCategory 수정
    - room의 ruleCnt 수정하는 부분 삭제
    - ruleCnt가 규칙 카테고리에 있으므로 삭제에서는 규칙 개수 수정은 안해줘도 됨.(어차피 규칙카테고리자체가 삭제될 것이므로)
  - [x] RuleService.createRuleCategory 수정
    - RuleCategoryResponseDto에 ruleCnt 추가
  - [x] RuleService.updateRuleCategory 수정
    - RuleCategoryResponseDto에 ruleCnt 추가
